### PR TITLE
Fix Schema typings

### LINKED ISSUE #1075: [BUG] TypeScript typings don't allow for array of types in Schema
### Summary:

The `type` property on Schema doesn't allow for arrays of types in TypeScript.

#### Schema
```ts
export const UserSchema = new Schema({
  // @ts-ignore    
  field1: { type: [String, Object], hashKey: true },
  // @ts-ignore
  field2: [String, Number],
});
```

### Current output and behavior (including stack trace):

```
ERROR in libs/database/src/user/user.schema.ts:7:14
TS2322: Type 'StringConstructor' is not assignable to type 'string'.
     5 |     id: { type: [String, Object], hashKey: true },
     6 |     field2: { type: String },
  >  7 |     field3: [String, Number],
       |              ^^^^^^
     8 |   },
     9 |   {
    10 |     saveUnknown: true,

ERROR in libs/database/src/user/user.schema.ts:7:22
TS2322: Type 'NumberConstructor' is not assignable to type 'string'.
     5 |     id: { type: [String, Object], hashKey: true },
     6 |     field2: { type: String },
  >  7 |     field3: [String, Number],
       |                      ^^^^^^
     8 |   },
     9 |   {
    10 |     saveUnknown: true,
```

### Expected output and behavior:

There are no Type errors

### Environment:

Node.js version (`node -v`): v14.13.0
TypeScript version (`tsc -v`): v4.1.2
NPM version: (`npm -v`): v6.14.8
Dynamoose version: v2.1.4

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

### PR DESCRIPTION
**Pull request by andrewda**
### Summary:

This PR updates the Schema typings to fix #1075. Adds `AttributeType[]` as a valid type for the `type` attribute and for the value of `SchemaDefinition`.

### GitHub linked issue:
Closes https://github.com/dynamoose/dynamoose/issues/1075

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have ensured the following commands are successful from the root of the project directory
  - [x] `npm test`
  - [x] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

File: lib/Schema.ts [hunk 1]
```diff
@@ -263,7 +263,7 @@ interface AttributeDefinition {
 	rangeKey?: boolean;
 }
 export interface SchemaDefinition {
-	[attribute: string]: AttributeType | AttributeDefinition;
+	[attribute: string]: AttributeType | AttributeType[] | AttributeDefinition;
```
Comment (fishcharlie) [inline lib/Schema.ts:266]:
```suggestion
	[attribute: string]: AttributeType | AttributeType[] | AttributeDefinition | AttributeDefinition[];
```

**Review by fishcharlie — CHANGES_REQUESTED** [review]
First of all, thanks so much for the PR! I think the biggest thing we need in order to merge this is automated tests. If you look in the `test/types` folder, you'll see a bunch of TypeScript tests that get type checked as part of our automated testing plan.

Write a few tests in there that fail without the changes you made, and pass with the changes you made.

**Comment by andrewda** [comment]
Thanks @fishcharlie, not sure how I missed that! Just pushed some tests, let me know if there are any other changes you'd like to see :+1:

**Review by fishcharlie — APPROVED** [review]
Thanks so much for this!!
