### PR TITLE
Fixing a bunch of issues with multiple types for attribute

### LINKED ISSUE #1064: Model.update breaks with multiple types  (repo to reproduce below)[BUG]
### Summary:
When using a schema with multiple types this error triggers on Model.update despite no Combine type being used. 
```
InvalidParameter: Combine type is not allowed to be used with multiple types.
```

to reproduce just 
```
git clone https://github.com/brunoargolo/dynamoose.git
npm i
npm run test -- test/unit/Model.js
```

Note a few tests will fail because I just updated the beforeEach as below:

```
describe("Model.update", () => {
	let User, updateItemParams, updateItemFunction;
	beforeEach(() => {
		- User = dynamoose.model("User", {"id": Number, "name": String, "age": Number});
                + User = dynamoose.model("User", {"id": Number, "name": String, "age": [Number, String]});
			
```

I did try to create a separate unit test but I'm not too familiar with those tests and it ended up with me getting a different exception than the one I got on my real project, while this reproduces it exactly.

#### Schema
```
{
   "id": Number, 
   "name": String, 
   "age": [Number, String]
}
```

#### Model
```
dynamoose.model("User", {"id": Number, "name": String, "age": [Number, String]});
```

#### General
```
// Code here
```

### Current output and behavior (including stack trace):
Model
       Model.update
         Callback
           Should send correct params to updateItem with $ADD and $SET update expression but $SET expression not as object:    
     InvalidParameter: Combine type is not allowed to be used with multiple types.
      at C:\dev\workspaces\ba-dynamoose\lib\Model\index.ts:103:8
      at Array.map (<anonymous>)
      at getUpdateExpressionObject (lib\Model\index.ts:103:8)
      at C:\dev\workspaces\ba-dynamoose\lib\Model\index.ts:104:18

### Expected output and behavior:
Tests should pass

### Environment:

Operating System: Windows 10
Operating System Version: 10.0.18363
Node.js version (`node -v`): 14.15.1
NPM version: (`npm -v`):  6.14.8
Dynamoose version: 2.4.1

### Other:
- [ x ] I have read through the Dynamoose documentation before posting this issue
- [ x ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ x ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ x ] I have tested the code provided and am confident it doesn't work as intended
- [ x ] I have filled out all fields above
- [ x ] I am running the latest version of Dynamoose

### PR DESCRIPTION
**Pull request by fishcharlie**
Closes #1064

### CODE REVIEW

**Comment by fishcharlie** [comment]
@brunoargolo Could you please review & test this PR?

File: test/unit/Model.js [hunk 1]
```diff
@@ -3565,6 +3565,32 @@ describe("Model", () => {
 					return expect(callType.func(User).bind(User)({"id": 1}, {"data1": "Charlie"})).to.be.rejectedWith("You must update all or none of the combine attributes when running Model.update. Missing combine attributes: data2.");
 				});
 
+				it("Shouldn't throw error if update with property allowing multiple types", async () => {
+					updateItemFunction = () => Promise.resolve({});
+					User = dynamoose.model("User", {"id": Number, "data": [String, Number]});
+
+					await callType.func(User).bind(User)({"id": 1}, {"data": "Bob"});
```
Comment (brunoargolo) [inline test/unit/Model.js:3572]: Since there arent other unit tests for multiple types, I'd recommend adding one more to make sure that passing a number the resulting sdk expression will reflect into a number. 
So an exact copy of this but of this test but with a number being passed instead.
```
await callType.func(User).bind(User)({"id": 1}, {"data": 2.5});
```

I've actually tested and it works fine, think thought it should be part of the suite.

**Review by brunoargolo — CHANGES_REQUESTED** [review]

File: test/unit/Model.js (hunk 1 above)
Comment (fishcharlie) [reply test/unit/Model.js:3572]: Fixed in 93480f88644683ba71ef31dbcc009b1d1533d639

**Comment by fishcharlie** [comment]
@brunoargolo Mind reviewing this again? 😃

**Review by brunoargolo — APPROVED** [review]
looks good. thanks!
