### PR TITLE
Document.original nested object fix

### LINKED ISSUE #922: [BUG] Document.original() seems to be changed sometimes
### Summary:
I've facing some issues with the "original" function on Document.
If i change any value o the document, the "original" keeps the original value, but if i change an array the original returns the changed array.

#### Schema
```
var VarsSchema = new Schema({
    _id: { type: String, hashkey: true, required: true }
}, {
    saveUnknown: true,
    timestamps: false
});
```

#### General
```
const Vars = require("myModel");
const newData = new Vars({
    _id: "xxx",
    arr: []
});
await newData.save();
const vars = await Vars.get({_id: "xxx"});
console.log(vars.original().arr);
vars.arr.push("value");
console.log(vars.original().arr);
```

### Current output and behavior (including stack trace):
result

### Expected output and behavior:
Both arrays with 0 length.

### Environment:

Operating System: OSX
Node.js version (`node -v`): 10.16.3
NPM version: (`npm -v`): 6.9.0
Dynamoose version: 2.2.1

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [X] I have tested the code provided and am confident it doesn't work as intended
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose

### PR DESCRIPTION
**Pull request by vlntdds**
### Summary:
Changing Object.Assign to JSON.parse/stringify to properly deep-clone the original object.

### GitHub linked issue:

Closes #922

### Type (select 1):
- [X] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [X] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [X] Yes
- [ ] No

### Other:
- [X] I have read through and followed the Contributing Guidelines
- [X] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [X] I have updated the Dynamoose documentation (if required) given the changes I made
- [X] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [X] I have ensured the following commands are successful from the root of the project directory
  - [X] `npm test`
  - [X] `npm run lint`
- [X] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [X] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [X] I have filled out all fields above

### CODE REVIEW

**Comment by vlntdds** [comment]
> We for sure need testing around this. Those tests should fail without this change and pass with this change.

Done!

File: test/Document.js [hunk 1]
```diff
@@ -1167,6 +1167,13 @@ describe("Document", () => {
 			expect(document.original()).to.eql({"id": 1});
 			expect({...document}).to.eql({"id": 2});
 		});
+
+		it("Shouldn't modify inner object after modifying document", () => {
+			const document = new model({"id": {"N": "1"}, "el": {"L": [{"S": "1"}]}}, {"type": "fromDynamo"});
+			document.el.push("2");
+			expect(document.original()).to.eql({"id": 1, "el": ["1"]});
+			expect({...document}).to.eql({"id": 1, "el": ["1", "2"]});
+		});
```
Comment (fishcharlie) [inline test/Document.js:1176]:
```suggestion
		it("Shouldn't modify inner array after modifying document", () => {
			const document = new model({"id": {"N": "1"}, "array": {"L": [{"S": "1"}]}}, {"type": "fromDynamo"});
			document.array.push("2");
			expect(document.original()).to.eql({"id": 1, "array": ["1"]});
			expect({...document}).to.eql({"id": 1, "array": ["1", "2"]});
		});

		it("Shouldn't modify inner object after modifying document", () => {
			const document = new model({"id": {"N": "1"}, "object": {"M": {"hello": {"S": "world"}}}}, {"type": "fromDynamo"});
			document.object.test = "item";
			expect(document.original()).to.eql({"id": 1, "object": {"hello": "world"}});
			expect({...document}).to.eql({"id": 1, "object": {"hello": "world", "test": "item"}});
		});
```
