### PR TITLE
dynamoose#961 Fix an issue where document.delete fails for rangeKey

### LINKED ISSUE #961: [BUG] Deleting Item with rangeKey & additional properties throws error
### Summary:
When trying to delete an item with rangeKey an error is raised.

### Code sample:
```
const dynamoose = require("dynamoose");

let testFunction = async () => {
  dynamoose.aws.sdk.config.update({
    region: 'local.region',
  });
  dynamoose.aws.ddb.local(); 

  const schema = {
    PK: { type: String, hashKey: true },
    SK: { type: String, rangeKey: true },
    someAttribute: { type: String }
  };

  const ExampleModel = dynamoose.model('TestTable', schema);

  await ExampleModel.create({
    PK: 'primarKey',
    SK: 'sortKey',
    someAttribute: 'someValue'
  });

  const example = await ExampleModel.get({
    PK: 'primarKey',
    SK: 'sortKey'
  });

  console.log(example);   // Document { SK: 'sortKey', someAttribute: 'someValue', PK: 'primarKey' }
  await example.delete();
};

testFunction();
```

### Current output and behavior (including stack trace):
Document { SK: 'sortKey', someAttribute: 'someValue', PK: 'primarKey' }
(node:25507) UnhandledPromiseRejectionWarning: ValidationException: **The number of conditions on the keys is invalid**
    at Request.extractError (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/svc/soltivo/tmp/dynamoose-error/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

### Expected output and behavior:
Document { SK: 'sortKey', someAttribute: 'someValue', PK: 'primarKey' }

### Environment:

Operating System: Ubuntu
Operating System Version: 20.04
Node.js version (node -v): v14.3.0
NPM version: (npm -v): 6.14.5
Dynamoose version: 2.2.1

### Other information (if applicable):

I am using local dynamodb: ([See this page](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html)) java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -inMemory

When checking the code in node_modules/dynamoose/dist/Model/index.js ([line 818](https://github.com/dynamoose/dynamoose/blob/v2.2.1/lib/Model/index.ts#L818)), I get the following output where no rangeKey is present.
```
{ Key: { PK: { S: 'primarKey' } }, TableName: 'TestTable' }
```

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [X] I have tested the code provided and am confident it doesn't work as intended
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose

### PR DESCRIPTION
**Pull request by abraxas**
### Summary:

Issue #961 reported that document.delete() and Model.delete(document) fails for documents with rangeKey.  The underlying cause is that document.delete 

#### Model
```
User = dynamoose.model("User", {"id": Number, "name": {"type": String, "rangeKey": true}});
```

#### General
```
user = User.get({"id": 1, "name": "Charlie", "type": "admin"});
await user.delete()
```

### GitHub linked issue:
Closes #961 
#---

### Other information:
This change appears to fix two real bugs with `delete` related to rangeKeys.

### Type (select 1):
- [X] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [X] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [X] Yes
- [ ] No

### Other:
- [X] I have read through and followed the Contributing Guidelines
- [X] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [X] I have updated the Dynamoose documentation (if required) given the changes I made
- [X] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [X] I have ensured the following commands are successful from the root of the project directory
  - [X] `npm test`
  - [X] `npm run lint`
- [X] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [X] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [X] I have filled out all fields above

### CODE REVIEW

File: lib/Document.ts [hunk 1]
```diff
@@ -111,9 +111,15 @@ export class Document {
 	delete(this: Document): Promise<void>;
 	delete(this: Document, callback: CallbackType<void, AWSError>): void;
 	delete (this: Document, callback?: CallbackType<void, AWSError>): Promise<void> | void {
-		return this.model.delete({
-			[this.model.getHashKey()]: this[this.model.getHashKey()]
-		}, callback);
+		const hashKey = this.model.getHashKey();
+		const rangeKey = this.model.getRangeKey();
+
+		const options = {[hashKey]: this[hashKey]};
```
Comment (fishcharlie) [inline lib/Document.ts:117]: Let's call this "key" instead of "options".

Comment (abraxas) [reply lib/Document.ts]: Pushed updated commit

**Review by sromano88-svc — APPROVED** [review]

**Review by fishcharlie — APPROVED** [review]
